In [1]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
a[2]

3

In [3]:
a[-1]

4

In [4]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[1:4]

array([2, 3, 4])

In [5]:
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b[6]=12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9])

In [10]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
c=np.array([13,14,15])
d=np.concatenate((a,c))

In [12]:
np.array_split(d,3)

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15])]

In [13]:
np.where(d==4)

(array([3], dtype=int64),)

In [14]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13], dtype=int64),)

In [15]:
c=np.array([10,5,7,3,9,6,4,2,8,1])
np.sort(c)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
c=np.array([[5,1,4,2],[2,4,1,3]])
np.sort(c)

array([[1, 2, 4, 5],
       [1, 2, 3, 4]])

In [17]:
veg=np.array(['mango','banana','orange','apple'])
np.sort(veg)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [18]:
np.random.randint(250)

206

In [19]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])